language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - OUNIT_CI=true
matrix:
  include:
    - name: "archive: linux"
      os: linux
      apt:
        packages:
          - libarchive-dev
      env: OCAML_VERSION=4.12 PACKAGE="archive"

    - name: "archive-lwt: linux"
      os: linux
      apt:
        packages:
          - libarchive-dev
      env: OCAML_VERSION=4.12 PACKAGE="archive-lwt"

    - name: "archive: MacOSX"
      os: osx
      env: OCAML_VERSION=4.12 PACKAGE="archive"
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew

    - name: "archive-lwt: MacOSX"
      os: osx
      env: OCAML_VERSION=4.12 PACKAGE="archive-lwt"
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
